#!/usr/bin/env bash
# Change home IP
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

echo "127.0.0.2 localhost" | tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | tee -a /etc/hosts
